/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Teatro;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author andresbaezrincon
 */
public class InicioInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form InicioInterfaz
     */
    DefaultListModel modelo = new DefaultListModel();
    InterfazTeatro interfaz = new InterfazTeatro();
    ArrayList<Float> listadoPrecios = new ArrayList<Float>();
    int indice = 0;
    public InicioInterfaz() {
        initComponents();
        btnIngresarPrecioAutomatico.setEnabled(false);
        btnIngresarPrecio.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnIngresoAutomatico = new javax.swing.JButton();
        btnPersonalizado = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        txtPrecioAutomatico = new javax.swing.JTextField();
        lbl2 = new javax.swing.JLabel();
        txtIncremento = new javax.swing.JTextField();
        btnIngresarPrecioAutomatico = new javax.swing.JButton();
        txtPrecioPersonalizado = new javax.swing.JTextField();
        lbl3 = new javax.swing.JLabel();
        lblFila = new javax.swing.JLabel();
        btnIngresarPrecio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Menlo", 1, 24)); // NOI18N
        jLabel1.setText("SALA DE TEATRO");

        jLabel21.setText("Ingrese el Método para asignar el valor a las filas:");

        btnIngresoAutomatico.setText("Ingreso Automático");
        btnIngresoAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoAutomaticoActionPerformed(evt);
            }
        });

        btnPersonalizado.setText("Ingreso Personalizado");
        btnPersonalizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalizadoActionPerformed(evt);
            }
        });

        lbl1.setText("Ingrese el precio de la fila más económica:");

        txtPrecioAutomatico.setEditable(false);

        lbl2.setText("Ingrese el incremento de fila en fila: ");

        txtIncremento.setEditable(false);

        btnIngresarPrecioAutomatico.setText("Ingresar Precio");
        btnIngresarPrecioAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarPrecioAutomaticoActionPerformed(evt);
            }
        });

        txtPrecioPersonalizado.setEditable(false);

        lbl3.setText("Ingrese el precio de la fila");

        lblFila.setText("A");

        btnIngresarPrecio.setText("Ingresar Precio");
        btnIngresarPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarPrecioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbl3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFila)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPrecioPersonalizado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnIngresarPrecio))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtIncremento, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                            .addComponent(txtPrecioAutomatico))
                                        .addGap(12, 12, 12)
                                        .addComponent(btnIngresarPrecioAutomatico))
                                    .addComponent(btnPersonalizado))
                                .addGap(0, 3, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIngresoAutomatico)
                            .addComponent(jLabel21))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnIngresarPrecio)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIngresoAutomatico)
                            .addComponent(btnPersonalizado))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl1)
                                    .addComponent(txtPrecioAutomatico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl2)
                                    .addComponent(txtIncremento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnIngresarPrecioAutomatico)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecioPersonalizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl3)
                                .addComponent(lblFila, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresoAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoAutomaticoActionPerformed
        // TODO add your handling code here:
    txtPrecioAutomatico.setEditable(true);
    txtIncremento.setEditable(true);
    btnIngresarPrecioAutomatico.setEnabled(true);
    }//GEN-LAST:event_btnIngresoAutomaticoActionPerformed

    private void btnPersonalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalizadoActionPerformed
        // TODO add your handling code here:
            txtPrecioPersonalizado.setEditable(true);
    txtPrecioPersonalizado.setEditable(true);
    btnIngresarPrecio.setEnabled(true);
    
    }//GEN-LAST:event_btnPersonalizadoActionPerformed

    private void btnIngresarPrecioAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarPrecioAutomaticoActionPerformed
        // TODO add your handling code here:
        llenado(Float.valueOf(txtPrecioAutomatico.getText()), Float.valueOf(txtIncremento.getText()));
        interfaz.listado = listadoPrecios;
       interfaz.setVisible(true);
    }//GEN-LAST:event_btnIngresarPrecioAutomaticoActionPerformed

    private void btnIngresarPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarPrecioActionPerformed
        // TODO add your handling code here:
    char letra = lblFila.getText().charAt(0);
    int fila = (int)letra;
    char palabra = (char)(fila+1);
    lblFila.setText(Character.toString(palabra));
    listadoPrecios.add(Float.valueOf(txtPrecioPersonalizado.getText()));
   if(listadoPrecios.size() == 15){
       interfaz.setVisible(true);
       interfaz.listado = listadoPrecios;
   }
    }//GEN-LAST:event_btnIngresarPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioInterfaz().setVisible(true);
            }
        });
        
    }
void llenado(float prec, float incremento){
    for(int i=0;i<15;i++)
          listadoPrecios.add(Float.valueOf(txtPrecioAutomatico.getText())+(i*incremento));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarPrecio;
    private javax.swing.JButton btnIngresarPrecioAutomatico;
    private javax.swing.JButton btnIngresoAutomatico;
    private javax.swing.JButton btnPersonalizado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lblFila;
    private javax.swing.JTextField txtIncremento;
    private javax.swing.JTextField txtPrecioAutomatico;
    private javax.swing.JTextField txtPrecioPersonalizado;
    // End of variables declaration//GEN-END:variables
}
