/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Teatro;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author andresbaezrincon
 */
public class InterfazTeatro extends javax.swing.JFrame {
    DefaultListModel modeloListaPrecio;
    DefaultListModel modeloListaAsientos;
    /**
     * Creates new form InterfazPrincipal
     */
   
    Asientos asientos = new Asientos();
    int precio = 0;
    int x=0;
    int y=0;
    int indice = 0;
    ArrayList<Float> listado = new ArrayList<Float>();
    public InterfazTeatro() {
        initComponents();
        btnIngresarPrecioAutomatico.setEnabled(false);
        btnIngresarPrecio.setEnabled(false);
        asientos.llenadoMatriz();
        modeloListaPrecio = new DefaultListModel();
        modeloListaAsientos = new DefaultListModel();
        jLista.setModel(modeloListaPrecio);
        jListaAsientos.setModel(modeloListaAsientos);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaMatriz = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        lblb = new javax.swing.JLabel();
        lblc = new javax.swing.JLabel();
        lbld = new javax.swing.JLabel();
        lble = new javax.swing.JLabel();
        lblf = new javax.swing.JLabel();
        lblg = new javax.swing.JLabel();
        lblh = new javax.swing.JLabel();
        lbli = new javax.swing.JLabel();
        lblj = new javax.swing.JLabel();
        lblk = new javax.swing.JLabel();
        lbll = new javax.swing.JLabel();
        lblm = new javax.swing.JLabel();
        lbln = new javax.swing.JLabel();
        lblo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        comboBoxColumna = new javax.swing.JComboBox<>();
        comboBoxFila = new javax.swing.JComboBox<>();
        btnComprar = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jLista = new javax.swing.JList<>();
        btnGenerarVentaTotal = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        btnIngresoAutomatico = new javax.swing.JButton();
        lbl3 = new javax.swing.JLabel();
        btnPersonalizado = new javax.swing.JButton();
        lblFila = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        btnIngresarPrecio = new javax.swing.JButton();
        txtPrecioAutomatico = new javax.swing.JTextField();
        lbl2 = new javax.swing.JLabel();
        txtIncremento = new javax.swing.JTextField();
        btnIngresarPrecioAutomatico = new javax.swing.JButton();
        txtPrecioPersonalizado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListaAsientos = new javax.swing.JList<>();
        btnBoletasVendidas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAreaMatriz.setEditable(false);
        txtAreaMatriz.setColumns(20);
        txtAreaMatriz.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        txtAreaMatriz.setRows(5);
        jScrollPane1.setViewportView(txtAreaMatriz);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("A");

        lblb.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lblb.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblb.setText("B");

        lblc.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lblc.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblc.setText("C");

        lbld.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lbld.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbld.setText("D");

        lble.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lble.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lble.setText("E");

        lblf.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lblf.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblf.setText("F");

        lblg.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lblg.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblg.setText("G");

        lblh.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lblh.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblh.setText("H");

        lbli.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lbli.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbli.setText("I");

        lblj.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lblj.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblj.setText("J");

        lblk.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lblk.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblk.setText("K");

        lbll.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lbll.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbll.setText("L");

        lblm.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lblm.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblm.setText("M");

        lbln.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lbln.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbln.setText("N");

        lblo.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lblo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblo.setText("O");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText("Comprar Asiento");

        jLabel6.setText("Seleccione la fila:");

        jLabel20.setText("Seleccione la columna:");

        comboBoxColumna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "10", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));

        comboBoxFila.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O" }));

        btnComprar.setText("COMPRAR");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        jLista.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jScrollPane4.setViewportView(jLista);

        btnGenerarVentaTotal.setText("VENTA TOTAL");
        btnGenerarVentaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarVentaTotalActionPerformed(evt);
            }
        });

        jLabel21.setText("Ingrese el Método para asignar el valor a las filas:");

        btnIngresoAutomatico.setText("Ingreso Automático");
        btnIngresoAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoAutomaticoActionPerformed(evt);
            }
        });

        lbl3.setText("Ingrese el precio de la fila");

        btnPersonalizado.setText("Ingreso Personalizado");
        btnPersonalizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalizadoActionPerformed(evt);
            }
        });

        lblFila.setText("A");

        lbl1.setText("Ingrese el precio de la fila más económica:");

        btnIngresarPrecio.setText("Ingresar Precio");
        btnIngresarPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarPrecioActionPerformed(evt);
            }
        });

        txtPrecioAutomatico.setEditable(false);

        lbl2.setText("Ingrese el incremento de fila en fila: ");

        txtIncremento.setEditable(false);

        btnIngresarPrecioAutomatico.setText("Ingresar Precio");
        btnIngresarPrecioAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarPrecioAutomaticoActionPerformed(evt);
            }
        });

        txtPrecioPersonalizado.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Menlo", 1, 24)); // NOI18N
        jLabel1.setText("SALA DE TEATRO");

        jScrollPane2.setViewportView(jListaAsientos);

        btnBoletasVendidas.setText("BOLETAS VENDIDAS");
        btnBoletasVendidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoletasVendidasActionPerformed(evt);
            }
        });

        jLabel2.setText("Precio por filas");

        jLabel5.setText("Asientos");

        jLabel7.setText("vendidos");

        javax.swing.GroupLayout lblaLayout = new javax.swing.GroupLayout(lbla);
        lbla.setLayout(lblaLayout);
        lblaLayout.setHorizontalGroup(
            lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblaLayout.createSequentialGroup()
                .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblaLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lblaLayout.createSequentialGroup()
                                .addComponent(btnGenerarVentaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBoletasVendidas, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addGroup(lblaLayout.createSequentialGroup()
                                .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(lblaLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(40, 40, 40)
                                        .addComponent(comboBoxFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(lblaLayout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboBoxColumna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnComprar))))
                    .addGroup(lblaLayout.createSequentialGroup()
                        .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lblaLayout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(lblaLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblb, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblc, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lble, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblf, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblg, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblk, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbll, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblm, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbln, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(lblaLayout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl2)
                                    .addGroup(lblaLayout.createSequentialGroup()
                                        .addGap(147, 147, 147)
                                        .addComponent(jLabel1))
                                    .addGroup(lblaLayout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnIngresoAutomatico)
                                            .addComponent(jLabel21)))
                                    .addGroup(lblaLayout.createSequentialGroup()
                                        .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbl1)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, lblaLayout.createSequentialGroup()
                                                .addComponent(lbl3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblFila)))
                                        .addGap(6, 6, 6)
                                        .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(lblaLayout.createSequentialGroup()
                                                .addComponent(txtPrecioPersonalizado)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnIngresarPrecio))
                                            .addGroup(lblaLayout.createSequentialGroup()
                                                .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(lblaLayout.createSequentialGroup()
                                                        .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(txtIncremento)
                                                            .addComponent(txtPrecioAutomatico, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(12, 12, 12)
                                                        .addComponent(btnIngresarPrecioAutomatico))
                                                    .addComponent(btnPersonalizado))
                                                .addGap(0, 3, Short.MAX_VALUE)))))))
                        .addGap(18, 18, 18)
                        .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(lblaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))))))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        lblaLayout.setVerticalGroup(
            lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblaLayout.createSequentialGroup()
                .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(lblaLayout.createSequentialGroup()
                                .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnIngresoAutomatico)
                                    .addComponent(btnPersonalizado))
                                .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(lblaLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lbl1)
                                            .addComponent(txtPrecioAutomatico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lbl2)
                                            .addComponent(txtIncremento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(lblaLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(btnIngresarPrecioAutomatico)))
                                .addGap(18, 18, 18)
                                .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrecioPersonalizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl3)
                                        .addComponent(lblFila, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(3, 3, 3))
                            .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(btnIngresarPrecio)))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblb, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblc, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbld, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lble, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblf, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblg, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblh, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbli, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblj, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblk, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbll, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblm, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbln, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblo))
                    .addGroup(lblaLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblaLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnComprar)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblaLayout.createSequentialGroup()
                        .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(comboBoxFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(comboBoxColumna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39)
                .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGenerarVentaTotal)
                        .addComponent(btnBoletasVendidas))
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(138, 138, 138))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbla, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // TODO add your handling code here:
        if(verificacion(comboBoxFila.getSelectedIndex(),comboBoxColumna.getSelectedIndex())==true){
        asientos.compraAsiento((char)(comboBoxFila.getSelectedIndex()+65), comboBoxColumna.getSelectedIndex());
        llenadoTextArea();
        llenadoCompra();
        asientos.ventas(comboBoxFila.getSelectedIndex());}
        
        
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnGenerarVentaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarVentaTotalActionPerformed
        // TODO add your handling code here
        ventaTotal();
        
    }//GEN-LAST:event_btnGenerarVentaTotalActionPerformed

    private void btnIngresoAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoAutomaticoActionPerformed
        // TODO add your handling code here:
        txtPrecioAutomatico.setEditable(true);
        txtIncremento.setEditable(true);
        btnIngresarPrecioAutomatico.setEnabled(true);
    }//GEN-LAST:event_btnIngresoAutomaticoActionPerformed

    private void btnPersonalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalizadoActionPerformed
        // TODO add your handling code here:
        txtPrecioPersonalizado.setEditable(true);
        txtPrecioPersonalizado.setEditable(true);
        btnIngresarPrecio.setEnabled(true);

    }//GEN-LAST:event_btnPersonalizadoActionPerformed

    private void btnIngresarPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarPrecioActionPerformed
        // TODO add your handling code here:
        char letra = lblFila.getText().charAt(0);
        int fila = (int)letra;
        char palabra = (char)(fila+1);
        lblFila.setText(Character.toString(palabra));
        asientos.preciosPersonalizados(Float.valueOf(txtPrecioPersonalizado.getText()));
        if(asientos.listaPrecios.size()==15){
        llenadoTextArea();
        llenadoPrecios(); 
        }
    }//GEN-LAST:event_btnIngresarPrecioActionPerformed

    private void btnIngresarPrecioAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarPrecioAutomaticoActionPerformed
        // TODO add your handling code here:
        asientos.preciosAutomaticos(Float.valueOf(txtPrecioAutomatico.getText()), Float.valueOf(txtIncremento.getText()));
        llenadoTextArea();
        llenadoPrecios();
    }//GEN-LAST:event_btnIngresarPrecioAutomaticoActionPerformed

    private void btnBoletasVendidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoletasVendidasActionPerformed
        // TODO add your handling code here:
        boletasVendidas();
    }//GEN-LAST:event_btnBoletasVendidasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazTeatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazTeatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazTeatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazTeatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazTeatro().setVisible(true);
            }
        });
    }
    
void llenadoTextArea(){
    txtAreaMatriz.setText("");
    for(int i=0;i<15;i++){
        for(int j=0;j<30;j++){
            if(j == 29)
            txtAreaMatriz.setText(txtAreaMatriz.getText()+asientos.matrizAsientos[i][j]); 
             else  
            txtAreaMatriz.setText(txtAreaMatriz.getText()+asientos.matrizAsientos[i][j]+" "); 
            txtAreaMatriz.setLineWrap(true);
        }   
    }
   txtAreaMatriz.setText(txtAreaMatriz.getText()+"                                        ESCENARIO "); 

}
void llenadoCompra(){
    modeloListaAsientos.addElement(asientos.listaAsientosOcupados.get(x));
        x++;
}


void llenadoPrecios(){
    for(int i=0;i<asientos.listaPrecios.size();i++){
        modeloListaPrecio.addElement(asientos.listaPrecios.get(i));
    }
}
void llenadoPreciosPersonalizados(){
    for(int i=0;i<asientos.listaPrecios.size();i++){
        modeloListaPrecio.addElement(asientos.listaPrecios.get(i));
    }
}
boolean verificacion(int i, int j){
    boolean retorno;
    if(asientos.matrizAsientos[i][j] == "#"){
        JOptionPane.showMessageDialog(null, "El asiento ya ha sido vendido");
        retorno = false;
    }
    else{
        JOptionPane.showMessageDialog(null, "Valor de la compra: "+String.valueOf(asientos.listaPrecios.get(i)));
        retorno = true;
    }
    return retorno;
}
void ventaTotal(){
    JOptionPane.showMessageDialog(null, "La venta total es: "+ String.valueOf(asientos.ventaTotal()));
}
void boletasVendidas(){
    JOptionPane.showMessageDialog(null, "El total de boletas vendidas es: "+ String.valueOf(asientos.cantidadAsientosVendidos));
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoletasVendidas;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnGenerarVentaTotal;
    private javax.swing.JButton btnIngresarPrecio;
    private javax.swing.JButton btnIngresarPrecioAutomatico;
    private javax.swing.JButton btnIngresoAutomatico;
    private javax.swing.JButton btnPersonalizado;
    private javax.swing.JComboBox<String> comboBoxColumna;
    private javax.swing.JComboBox<String> comboBoxFila;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jLista;
    private javax.swing.JList<String> jListaAsientos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lblFila;
    private javax.swing.JPanel lbla;
    private javax.swing.JLabel lblb;
    private javax.swing.JLabel lblc;
    private javax.swing.JLabel lbld;
    private javax.swing.JLabel lble;
    private javax.swing.JLabel lblf;
    private javax.swing.JLabel lblg;
    private javax.swing.JLabel lblh;
    private javax.swing.JLabel lbli;
    private javax.swing.JLabel lblj;
    private javax.swing.JLabel lblk;
    private javax.swing.JLabel lbll;
    private javax.swing.JLabel lblm;
    private javax.swing.JLabel lbln;
    private javax.swing.JLabel lblo;
    private javax.swing.JTextArea txtAreaMatriz;
    private javax.swing.JTextField txtIncremento;
    private javax.swing.JTextField txtPrecioAutomatico;
    private javax.swing.JTextField txtPrecioPersonalizado;
    // End of variables declaration//GEN-END:variables
}
